### ISSUE TITLE
Reminder not showing up

### ISSUE THREAD

**Issue by kumareshr** [uphy/obsidian-reminder#1]
![image](https://user-images.githubusercontent.com/22025054/129592908-5fb67ca3-8bd6-419c-baf4-af177119a779.png)
tired to set reminders and list the reminder as give in the readme. seems not working 

![image](https://user-images.githubusercontent.com/22025054/129593076-1c7ec018-66f8-4df4-b5aa-561fe0781013.png)

did I missed anything !?

Thanks for developing this plugin :)

**Comment by uphy** [comment]
Thanks for using!
