### ISSUE TITLE
[Bug]: Reminders do not work when not attached to a task

### ISSUE THREAD

**Issue by kLy** [uphy/obsidian-reminder#103]
### Describe the bug

Seems like reminders only work (the popup insertion, the reminder itself, etc) only when it's attached to a task "- [ ]". This does seem like buggy behaviour since we'd want reminders on all sorts of things, not just tasks.

### Steps to reproduce

- Type (@ next to a non-task line and pick a date... no insertion happens
- Wait for the date of a particular reminder on a non-task line. See that there's no reminder actually being fired.

### Operating system

macOS

**Comment by uphy** [comment]
duplicate #43
