### ISSUE TITLE
[Feature]: sticky notification 

### ISSUE THREAD

**Issue by johans3** [uphy/obsidian-reminder#104]
### Goal or desired outcome of this feature

My system: MacOS 

I really like Notifications, but sticky notifications, with dismiss / later buttons

Default `banner notifications` disappear too quickly and don't allow any customization 

### Describe the feature

Sticky notifications gives us the opportunity to decide how to handle tasks, eg now or later. 

In addition, sticky notifications are visible, that's very important, because if we aren't paying  attention because of little distractions or we're away from the screen for a moment, we will miss our reminders.
And that's the opposite of what a reminder should be doing, eg to remind us to do something. 

how is `Reminders` calling notifications? applescript won't do the trick, because it's properties are insufficient, too basic

**Comment by johans3** [comment]
I found out, we just need to open system preferences, notifications and change notification settings of Obsidian from banner to alert 

Maybe you could add this info to the readme of your plugin?

**Comment by uphy** [comment]
See also:
https://uphy.github.io/obsidian-reminder/guide/notification.html
