### ISSUE TITLE
Page based reminders

### ISSUE THREAD

**Issue by aviral-batra** [uphy/obsidian-reminder#12]
Hi, nice plugin.

I had a feature request - for the reminders dialog to be opened when a certain page was opened. These could be specified in the same format as the date reminders i.e. ```(@[[Page linked to reminder]])```. This could be in addition to a reminder being linked to a date or time.

**Comment by uphy** [comment]
Could you tell me how use page-based reminder feature?
I have no idea to use the feature.

**Comment by aviral-batra** [comment]
So you know the way reminders are linked to dates? They pop up when the date/time has come. In a similar way, this would open when you open a certain page.

Example use case - you have a page on walking dogs, which you look at before you walk the dog. This time you remember, you have to go to the shop on the way too to get dog food. So you add a page-linked reminder in the format 

```
- [ ] Buy dog food on next walk (@[[Dog walking]])
```

which will show the reminder when you next open the page ```Dog walking```.

If I'm still not making sense, when I have time I will just open a pull req and show you what I mean.

**Comment by uphy** [comment]
Thank you for your explanation!

But I write the TODO item (dog food) to Dog walking page in that case.
How does it help more than plain TODO item?

**Comment by aviral-batra** [comment]
I think there would be a few benefits:

- You are more likely to see important information if it pops up otherwise if you are casually scrolling you will look over it
- If you have a lot of information on that page, having the reminders pop up is more efficient than looking for them
- You can put these todos anywhere e.g. you could write all your todos in your daily note but also link them to pages
- You might have a lot of todos e.g. for a project but a few things you need to urgently do - this is easier than dividing the tasks up with a header, then making it stand out etc. the urgent todos could otherwise get lost in the rest

And you could turn it on and off which would make it a choice if people didn't want to be annoyed if they needed to look through stuff quickly but would be useful when working through things so you do not forget and it is comprehensive.

**Comment by uphy** [comment]
Thanks for providing the benefits.  And sorry for the late reply.
I've been using this plugin for a long time, but I still didn't think I needed this feature.
I don't want to implement this feature to keep the implementation of this plugin simple.

If there are many others with the same request, I will consider support again.

**Comment by peepopoggers** [comment]
This might actually be a nice feature, just for customizability. >.<
