### ISSUE TITLE
Nicer icon for reminders in the side bar

### ISSUE THREAD

**Issue by Cito** [uphy/obsidian-reminder#13]
Currently, the tab for the reminders has a very general "document" icon. It would be easier to recognize the tab if the icon was a bit more specific, e.g. a clock icon like in the [recent files plugin](https://github.com/tgrosinger/recent-files-obsidian) or maybe even better a bell or alarm clock icon.

**Comment by uphy** [comment]
Used `clock` icon instead in v1.0.3.
Thank you.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/1233373/131272157-1c03e92e-2c7f-444b-91a5-f6e8924db76b.png">

**Comment by Cito** [comment]
Nice, thank you!
