### ISSUE TITLE
[Bug]: Reminder date not appearing when I select a date from the popup calendar

### ISSUE THREAD

**Issue by esmith1226** [uphy/obsidian-reminder#155]
### Describe the bug

When I type (@, the popup calendar appears.  When I select a date, nothing happens.  I just see this: 

> Item to be reminded (@ 

### Expected Behavior

I should see a date next to the line entry: 

>  - Reminder item (@2023-07-01)

If it's a todo item with a reminder it should look like this:

> [  ] Todo Item (@2023-07-01)

### Steps to reproduce

Here's how I have the trigger set up in the settings:
![Screenshot 2023-07-01 112449](https://github.com/uphy/obsidian-reminder/assets/138323373/79faf62b-877e-48a5-8db4-4d484a214b86)

### Operating system

Windows

**Comment by worstestes** [comment]
running into this now, is this fixed?

OS
macos

**Comment by mg** [comment]
Same, no date is inserted when I click the day in the calendar popup. Was it fixed or was this some user error?

**Comment by wakywayne** [comment]
I am having this issue as well @uphy was this ever fixed?
