### ISSUE TITLE
mobile reminder

### ISSUE THREAD

**Issue by imeed166** [uphy/obsidian-reminder#16]
Hi again, can you add support for mobile reminders ? I tried setting a reminder in android but nothing showed up except for the in-app reminder. 
- Obsidian was allowed to display notifications
- The plugin's setting for "system notification" was enabled

**Comment by hajnalbendeguz** [comment]
Great plugin. What's the status on iOs?

**Comment by uphy** [comment]
Unfortunately, It’s not possible as far as I know.
Because Obsidian API doesn’t provide system notification feature.

If it is possible, I’d like to implement mobile notification.

**Comment by uphy** [comment]
Also, I should document this in setting screen or readme

**Comment by polak-jan** [comment]
Sorry for reviving an old and closed issue but I think I have a reasonably simple solution for this, at least as a temporary thing until Obsidian adds support for it.

The solution would be to have either an official or an officially endorsed app that is separate from Obsidian. You would point this app at your vault and it would do its own pass to search for reminder sequences in the background and set up notifications for them.

I am considering giving this approach a go myself, but I only have experience with Android development, and much of it at that. So I would only make an Android app.

**Comment by uphy** [comment]
@polak-jan Thank you for your idea!  In fact, as it happens I am currently developing it.
Because it is developed with flutter, it may also supports iOS.

I don't know when the release will be, but please wait until then.

**Comment by polak-jan** [comment]
That's great, can't wait! Any idea in roughly what time frame we could expect to see it?

**Comment by uphy** [comment]
It will take 1 month ~ 3 months.

I've implemented base features, scanning reminders in a vault periodically, system notification.
Currently I'm testing it and developing integration with Obsidian Reminder Plugin(via URI scheme).

Would you like to use the version under development? (e.g., via Google Play Store beta app)
Maybe I can provide it in this month.

**Comment by uphy** [comment]
Also, I possibly makes the it a paid application when I release it as production version.

**Comment by polak-jan** [comment]
I definitely wouldn't mind testing it.

And personally I don't mind it being paid as long as it's a reasonable price, was actually going to ask for a way to donate to you anyway :)

**Comment by imeed166** [comment]
I'm up for testing too.

**Comment by uphy** [comment]
Obsidian uses Capacitor as mobile app framework and it's based on web browser. 
I'm not sure but it may support the feature.

However, my motivation is low because it only supports iOS.

**Comment by polak-jan** [comment]
Are there any news on the app?

**Comment by samuk10** [comment]
> this might help https://ntfy.sh/

do you made it to work?

Found this too: https://github.com/the-argus/obsidian-tasks-ntfy
