### ISSUE TITLE
support for obsidian-tasks recurring date

### ISSUE THREAD

**Issue by imeed166** [uphy/obsidian-reminder#17]
When enabling "reminder plugin format" in the settings and completing a recurring task created by the "obsidian-tasks" via the reminder, the task plugin doesn't create a new task with the new recurring date.

**Comment by uphy** [comment]
Supported this feature in 1.0.8 experimentally.
Can you try it?

**Comment by imeed166** [comment]
still doesn't work, with "reminder plugin format" enabled in setting, the new task isn't created.

https://user-images.githubusercontent.com/38974541/132829574-4075fd73-2e32-4f4e-8398-da12e750acdb.mov

![image](https://user-images.githubusercontent.com/38974541/132829631-14f99ccf-16dd-4af4-bfb2-e7f2c18333d6.png)

**Comment by uphy** [comment]
Umm... I don't expect combination of Tasks plugin format and Reminder plugin format.
At least currently, you must use consistent format like this

```
- [ ] test 🔁 every weekday 📅 2021-09-11
```

**Comment by uphy** [comment]
Recurring date is Tasks-Plugin-specific feature.

When you input `(@2021-09-10 10:04)`, this plugin recognizes as `Reminder Plugin Format`.
So recurring date feature is not enabled.

How about introducing another emoji for Tasks Plugin Format like this? (not implemented yet! just a suggestion.)

```
- [ ] test 🔁 every weekday 📅 2021-09-11 🕐 2021-09-10 10:04
```

Reminder plugin recognizes this as Tasks plugin, and recurring date feature will be enabled.

**Comment by imeed166** [comment]
Yes, this is a good suggestion, I don't use the task plugin format because I can't add a time to the reminder. But with this suggestion, it'll be possible. 
I'll be waiting for this implementation, thank you.

**Comment by uphy** [comment]
@imeed166 Introduced custom emoji(⏰) to Tasks Plugin format in v1.1.0.

e.g.

```md
- [ ] Task 2 ⏰ 2021-09-14 20:00 🔁 every day 📅 2021-09-15 
```

Also you can toggle TODO with <kbd>Command</kbd> + <kbd>Shift</kbd> + <kbd>Enter</kbd>.

**Comment by uphy** [comment]
@imeed166 forgot to say.  You need to update setting.
![Uploading image.png…]()

**Comment by imeed166** [comment]
It works great, thank you. Though it should be documented that when you only add the reminder without the date like this `task name + ⏰ YYYY-MM-DD HH:mm`, obsidian-tasks doesn't recognize it, so you can't see it when [querying tasks](https://github.com/schemar/obsidian-tasks#querying-and-listing-tasks) unless you re-add the date like this `task name + ⏰YYYY-MM-DD HH:mm + 📅 YYYY-MM-DD`. Also, the order is important, the `📅 date` have to be last for it to be recognized.

I don't know if this should be added in the documentation of this plugin or obsidian-tasks plugin. @schemar what do you think ?

**Comment by uphy** [comment]
Thank you for the review!

> when you only add the reminder without the date like this task name + ⏰ YYYY-MM-DD HH:mm, obsidian-tasks doesn't recognize it

I feel it shouldn't be recognized as a reminder.
This feature was introduced for interoperability with Tasks Plugin.
As far as Tasks Plugin doesn't recognize it as a task, it shouldn't be recognized as a reminder.

> the order is important

This should be added in the documentation of this plugin because this(⏰) is Reminder Plugin's own spec currently.
I will document it.
