### ISSUE TITLE
[Bug]: obsidian-reminder.cf site no longer exists

### ISSUE THREAD

**Issue by tescher** [uphy/obsidian-reminder#172]
### Describe the bug

references to obsidian-reminder.cf in the Readme and elsewhere. That site no longer exists

### Expected Behavior

Either revive the site or fix the documentation here

### Steps to reproduce

Click on obsidian-reminder.cf

### Operating system

Linux

**Comment by lunule** [comment]
Not Linux specific. The site obsidian-reminder.cf is totally down, independently of the OS and browsers used.
Seems to be a hosting issue.

**Comment by uphy** [comment]
I apologize for any inconvenience caused.
Due to domain expiration, obsidian-reminder.cf has been moved to the following URL:
https://uphy.github.io/obsidian-reminder/
