### ISSUE TITLE
notification popup improvements - link to file #enhancement

### ISSUE THREAD

**Issue by jroachgit** [uphy/obsidian-reminder#18]
Hi,
Great work on this plugin.
Are you able to add a link on the notification popup to take you to the file?

**Comment by uphy** [comment]
That's a feature I wanted too.

But currently reminder notification is implemented as a modal.
So when you click the link in the modal, the modal will be closed or hard to see the link destination page.
I am wondering what UI to use for reminder.

**Comment by uphy** [comment]
@jroachgit Added link to file in reminder modal in v1.1.0.
Please try to click file path in reminder modal.

When you click the file path, the file will be appeared and the modal is closed.
The reminder is muted once and moved to `Overdue` section in reminder list view.

**Comment by uphy** [comment]
Since there is no response, I'm closing this once.
Please reopen if there is anything.
