### ISSUE TITLE
notification popup improvements -  default remind me later value w/ 'Snooze' button

### ISSUE THREAD

**Issue by jroachgit** [uphy/obsidian-reminder#19]
Hi!
Are we able to have a default remind me later value, and have a snooze button?

You could also keep the current behaviour of when the user selects a time, it snoozes for that duration.

**Comment by uphy** [comment]
You can use escape key or click out of the reminder modal to close it.
When the reminder modal is closed(canceled), the reminder will be shown 10 minutes later again.

I have a plan to change the time with setting.
Is this satisfies your request?

**Comment by uphy** [comment]
@jroachgit From v1.1.0, you can mute the reminder by `Esc` key in reminder modal or clicking out of the reminder modal.
Muted reminders can be seen in Overdue section of reminder list view.
When you click the reminder in Overdue section, you can check with reminder modal.

Is snooze button needed?  If yes, can you tell me why you need snooze button?

**Comment by uphy** [comment]
There is no update for a while, so close it once. Please reopen if necessary.
