### ISSUE TITLE
when using the 'Tasks' plugin - when a task is overdue and the 'reminder' is triggered, ignoring or snoozing partially completes the task. Marking as done does not complete the action for tasks created via "Tasks"

### ISSUE THREAD

**Issue by jroachgit** [uphy/obsidian-reminder#20]
## Expected Behavior
1) a new task is created, via the task modal:
![image](https://user-images.githubusercontent.com/35711815/132350733-c36ab68c-b8a1-4d8d-9493-b23a7f58e024.png)

NB: todays date is the 2021-09-07

When the notification pops up, and is ignored, the task should remain as excepted, eg:
![image](https://user-images.githubusercontent.com/35711815/132350660-615776df-a052-40d1-ad3d-e609c6c70ce1.png)

2) when 'Mark as Done' is selected, [x] should appear with the green tick and today's date

## Current Behavior
1) The green tick with today's date appears, yet, the box isn't ticked, but the task modal says done w/ today's date.

![image](https://user-images.githubusercontent.com/35711815/132350910-987dc25a-6564-48f7-ac90-0315e6c08bfa.png)

![image](https://user-images.githubusercontent.com/35711815/132350936-d9161a0a-7bc4-4657-95e1-1e447e6615be.png)

2) the [ ] remains, yet the green tick and today's date appears.

## Context (Environment)
* Obsidian version: 0.12.15
* Tasks version: 1.3
* Reminder version: 1.0.7
* [ ] I have tried it with all other plugins disabled and the error still occurs

**Comment by uphy** [comment]
Oh, there was a bug.
I will fix it in the next release.

**Comment by uphy** [comment]
I've fixed this bug with v1.0.8.

In this release, I also added `Primary reminder format` and `Calendar popup trigger`.
I think they will come in handy for you.
