### ISSUE TITLE
In-App Popup Notification Stopped Working on Mobile

### ISSUE THREAD

**Issue by foss-guru** [uphy/obsidian-reminder#206]
### Describe the bug

When I first started using the Reminder plugin, the overdues would trigger the popup notification in the mobile app with no issue. Semi-recently however they've mysteriously stopped triggering. 

### Expected Behavior

When a task is overdue, should issue an in-app popup notification.

### Steps to reproduce

1. Install the plugin and add a reminder with an upcoming trigger date.
2. Open the app when a reminder is overdue.
3. Observe no popup notification issued (or like me, go weeks on end before realizing, hey didn't it used to issue these? 😵)

Regarding that last parenthetical, it took me a while to notice because they still issue just fine for me on Windows.

I tried checking for updates both for the base app (version 1.7.7) and by checking for plugin updates in the app. I also have the plugin enabled in the app. Checked for system updates, stopping and clearing app cache all that as well. Still doesn't do popups.

### Operating system

Android

**Comment by vavilondev** [comment]
I am also not able to get notifications

**Comment by foss-guru** [comment]
After reading a few more threads, realized I was never opening the reminders tab in the app (left swipe). This started triggering the overdue items again. Hard to tell if there was more to it or not but maybe I did have some outdated app data reset when I opened the menu again Idk. 🤷‍♂️
