### ISSUE TITLE
Snooze values in list doesn't 'stick' when edited and closed

### ISSUE THREAD

**Issue by jroachgit** [uphy/obsidian-reminder#21]
Hi,

Adding:
Friday
Saturday
Sunday
Next Tuesday

in all or a combination does not stay in this box, nor is selectable on the notification popup.
![image](https://user-images.githubusercontent.com/35711815/132356534-411dbe41-5808-46f1-ad9d-c181a5ab1cd6.png)

**Comment by uphy** [comment]
This plugin doesn't support `Friday`, `Saturday`, `Sunday`. 

- In N minutes (minute)
- In N hours (hour)
- Next (Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday)
- Next day
- Next week
- Next month
- Next year
- Tomorrow

It should be documented.

**Comment by jroachgit** [comment]
Gotcha! thanks for the info!
