### ISSUE TITLE
Notification on top of Obsidian doesn't snooze despite clicking snooze

### ISSUE THREAD

**Issue by jroachgit** [uphy/obsidian-reminder#23]
As a user
and a task reminder pops up 
and the user is viewing obsidian
When the user closes the popup
OR
When the user selects a time value (eg 15mins)
And the window disappears
THEN within 10seconds to 30seconds, the same popup appears addressing the same task and the same note (as per file address).

--
if silencing/snoozing is reattempted, the popup keeps appearing; my solution was to disable the plugin.

**Comment by uphy** [comment]
Please provide the TODO and setting to reproduce.

**Comment by ackstorm23** [comment]
I've observed this problem too, although it comes back from snooze in a few seconds, and no matter how many times I re-snooze it keeps popping up a window that blocks the interface.

**Unless**  I snooze until **tomorrow** or **complete**. 

It always catches me an inopportune moment so I have not been able to come up with evidence.  I'll try to stop and gather next time it happens.

**Comment by uphy** [comment]
Sorry for the inconvenience.
Can you tell me the which format you are using? (Default / Tasks Plugin / Kanban Plugin)

**Comment by uphy** [comment]
Also, please check if you are using latest version(1.0.8).

<img width="600" alt="image" src="https://user-images.githubusercontent.com/1233373/133179161-6cd821f5-358b-4f1c-95ca-2bb753a599c8.png">

**Comment by ackstorm23** [comment]
- I just updated to 1.0.8 today so we'll see.  
- I have all of the task formats enabled, but the primary reminder format is the plugin's format. 
- I do use the tasks plugin, and I also use the daily rollover plugin.

**Comment by uphy** [comment]
@ackstorm23 Thank you for the info.  If the issue has reproduced, I will fix soon.
