### ISSUE TITLE
[Bug]: Pop-up of calendar date picker goes underneath other panes, should be above

### ISSUE THREAD

**Issue by michael-imbeault** [uphy/obsidian-reminder#24]
### Describe the bug

I have my todo list set in the left sidebar as a page that's always open - using the calendar date picker when the line is close to the next pane (my central one) results in the pop-up being half underneath the next pane, making it impossible to select a date.

### Expected Behavior

Calendar date picker should be displayed above any other pane.

### Steps to reproduce

Create a note, put it on the left sidebar (not just on left side of the current note, but in the side-bar you can collapse), write some text to get close to the edge of the main pane, hit (@ to summon the calendar date picker, notice its underneath the main pane.

### Operating system

Windows

**Comment by uphy** [comment]
Thank you for the report.  I fixed that problem in v1.1.1.

**Before fix**
<img width="922" alt="image" src="https://user-images.githubusercontent.com/1233373/134462435-aba9ff3f-9179-456d-a069-1f459e953fb0.png">

**After fix**
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/1233373/134462478-d2137f7f-8529-41cc-be3d-d3ac621a74a4.png">

**Comment by davebhc71** [comment]
Please review the item mentioned below at the same time since it seems to be another issue with the Calendar pop-up!

https://github.com/uphy/obsidian-reminder/issues/34#issue-1033793124

**Comment by uphy** [comment]
Fixed.  Also the calendar popup works on mobile now.
So I close this issue.
