### ISSUE TITLE
[BUG]:With the release of v1.1.1, I can install the mobile version, but it is no longer enabled.

### ISSUE THREAD

**Issue by rakugakijin** [uphy/obsidian-reminder#25]
I look forward to working with you.

**Comment by rakugakijin** [comment]
When I upgraded to the mobile version, it installed but was disabled.

**Comment by uphy** [comment]
@rakugakijin Thank you for the report!
I've reproduced the issue but I couldn't find out why it cannot be loaded.
I will investigate this in detail later and try to fix it.

**Comment by rakugakijin** [comment]
I was able to install it. After that, when I enabled it, it became disabled instead of enabled.![image](https://user-images.githubusercontent.com/65814903/134845242-adc64784-66b9-4df9-8883-da82ad708303.jpeg)

**Comment by vincentteoh** [comment]
I have the same problem.

**Comment by rakugakijin** [comment]
What is the difference between reminder 1.1.1 and 1.1.0?  When I go down to 1.1.0, it works on mobile.

**Comment by uphy** [comment]
Please try v1.1.2

**Comment by vincentteoh** [comment]
> Please try v1.1.2

Thanks! It works well on my Samsung phone.
