### ISSUE TITLE
[Bug]: time in repeating tasks follows postpone rather than original time

### ISSUE THREAD

**Issue by imeed166** [uphy/obsidian-reminder#26]
### Describe the bug

I'm using the task plugin with the reminder plugin. I have a repeating reminder (every day at 22:09, for example). Say i postpone it for 1 minute. After completion, the new task include 22:10 rather than 22:09.

https://user-images.githubusercontent.com/38974541/134986242-da7f4ac4-9c19-49f5-85af-0bd75081027b.mov

### Expected Behavior

The newly created task should have the original time rather than the postponed time.

### Steps to reproduce

Create a repeating task with reminder then postpone it, then complete it. The new task will include the postponed time rather than the original time.

### Operating system

macOS

**Comment by uphy** [comment]
relates to https://github.com/uphy/obsidian-reminder/issues/11

**Comment by uphy** [comment]
This is because the reminder plugin calculates the time to postpone based on the current time.
I have a plan to change the behavior by setting.
Please wait for the future.

**Comment by uphy** [comment]
I'm closing this issue.  Please track #11.
