### ISSUE TITLE
[Bug]: when completing repeating task, the reminder date doesn't change

### ISSUE THREAD

**Issue by imeed166** [uphy/obsidian-reminder#27]
### Describe the bug

I'm using the [task plugin](https://github.com/schemar/obsidian-tasks) with the reminder plugin, I created a repeating task with a reminder. Sometimes I want to complete the task before the reminder triggers, but the reminder date doesn't change to the next recurrence. The recurrence only change when I complete it from notification or obsidian pop up

https://user-images.githubusercontent.com/38974541/134984954-eb852636-255b-4567-97fc-3874934d9019.mov

### Expected Behavior

The reminder date should change to the next recurrence.

### Steps to reproduce

Create a repeating task with a reminder, then complete it before the reminder triggers.

### Operating system

macOS

**Comment by uphy** [comment]
The completing action is provided by Tasks Plugin.
Of course Tasks plugin doesn't support ⏰ emoji.

Instead, you can toggle check list status by <kbd>⌘</kbd> + <kbd>Shift</kbd> + <kbd>Enter</kbd> in editor mode.

**Comment by imeed166** [comment]
I see, thank you for the explanation.
