### ISSUE TITLE
[Bug]: [windows] No menu displayed if system notif is enabled

### ISSUE THREAD

**Issue by Mara-Li** [uphy/obsidian-reminder#31]
### Describe the bug

The menu to choose to link, mute, mark as done, doesn't appear if I enable the system notification. 

### Expected Behavior

When I click on the menu, the menu must appear. 

### Steps to reproduce

- Enable system notification
- Click on overdue reminder

### Operating system

Windows

**Comment by uphy** [comment]
I can't reproduce it because I don't have Windows machine.
Can you provide me a screenshot?

I do not understand the `menu` you mentioned.

**Comment by imeed166** [comment]
If I understand correctly, to get this menu, you just have to click on the notification when it appears.

![image](https://user-images.githubusercontent.com/30244939/137936386-bb304a2a-9d46-46ed-8e35-f0334e9ba9b5.png)

**Comment by Mara-Li** [comment]
Yeah, but it don't work if I enable system notification.

**Comment by uphy** [comment]
@Mara-Li That would be fatal😢
Can you provide me the console log?

(1) Toggle Developer Tools
<img width="405" alt="image" src="https://user-images.githubusercontent.com/1233373/138006417-e8a815cb-1838-4feb-86e4-6a55405299fe.png">
(2) Check all options of the logging level

(3) Copy the logs and send me them

<img width="404" alt="image" src="https://user-images.githubusercontent.com/1233373/138006520-4cce6f55-3ffe-44ba-8f6d-5f17a043e64e.png">

**Comment by Mara-Li** [comment]
https://www.loom.com/share/60b0090a92514908a1c947f9085891a5
I take a recording because I don't know what I must send you !
