### ISSUE TITLE
[Feature]: Exclude folder

### ISSUE THREAD

**Issue by Mara-Li** [uphy/obsidian-reminder#33]
### Goal or desired outcome of this feature

Doesn't have notification at all for file in specific folder (as templater folder for example)

Why ? Because I create a custom reminder in a template, and each day, this template is overdue.… Not very practical! 

### Describe the feature

The file in the folder specified doesn't must appear in the reminder menu and be reminded.

**Comment by Mara-Li** [comment]
Well, in this case, it can be a problem with templating, BUT ! i can totally remove it with js in the templater. So, yes, it can totally work for my problem 😀

**Comment by TangdizhiH** [comment]
> 

Hello, I'm running into the same problem as well, but I have little knowledge about JS, could you please show me how to remove it when creating from the template? thanks!
