### ISSUE TITLE
[Bug]: Calendar pop-up does not work on mobile devices

### ISSUE THREAD

**Issue by richardlm** [uphy/obsidian-reminder#34]
### Describe the bug

The calendar popup does not work on Android, even if I set the trigger text to something simple. 

### Expected Behavior

Setting trigger text such as xxxxx works on Obsidian desktop but not Android.

### Steps to reproduce

On Android:
Configure Reminder to work with Tasks
Set trigger text to xxxxx
Create a reminder and enter xxxxx

### Operating system

Android

**Comment by davebhc71** [comment]
Isn’t working at all on iPad. Is that a known issue that I missed somewhere?

**Comment by uphy** [comment]
Calendar popup seems to be implemented using an API that doesn't work on mobile devices.

- https://github.com/uphy/obsidian-reminder/blob/68d9cc50da7ddba137249a5e6baec0749f36686b/src/main.ts#L81-L94
- https://github.com/uphy/obsidian-reminder/blob/68d9cc50da7ddba137249a5e6baec0749f36686b/src/ui/datetime-chooser.ts#L50

Further research is needed on how to implement it, and it will take some time to resolve.

**Comment by davebhc71** [comment]
Thanks for reply. Shame the current method doesn’t work on Mobile Devices. How about if you ‘called’ the Calendar pop-up from a Hotkey????

**Comment by uphy** [comment]
It's same.  Calendar popup from a hotkey also use APIs not work in mobile devices.

**Comment by uphy** [comment]
For mobile, I gave up on popup triggered by input text.
Instead, as you said, I'm implementing with a command to show the calendar popup.

![Kapture 2021-11-02 at 21 20 41](https://user-images.githubusercontent.com/1233373/139845044-e7343edc-7369-4fe7-8bff-97e2ac75ef28.gif)

**Comment by davebhc71** [comment]
GREAT!!! Looking forward to it!!

**Comment by uphy** [comment]
@davebhc71 @richardlm Mobile support for calendar popup is available in v1.1.3.

It is useful to register the command as a toolbar button as shown in the video above.

1. Options > Mobile
2. Configure
3. Select the command named `Show calendar popup`

**Comment by davebhc71** [comment]
There was no “video above” to register the Command as a Toolbar button in the email I received. I’ve tried to use the instructions 1,2, and 3, but there is no “Show Calendar Popup”

Davebhc71

**Comment by davebhc71** [comment]
﻿
﻿
Ignore my previous email. I was able to Configure Mobile Quick Action with the Show Calendar Popup BUT I don’t think that’s the most convenient/ proper place for it to appear. I would much prefer to have it as one of the options the Mobile Tool Bar that is always visible above the keyboard. Just a suggestion!

Davebhc71

**Comment by davebhc71** [comment]
Never Mind …….. I was able to ADD it to the Command Palette! Sorry for the confusion. Works like a charm. Thanks for your work!

Davebhc71

**Comment by uphy** [comment]
Thank you for your report! I close this issue.
