### ISSUE TITLE
[Feature]: recurrent reminder

### ISSUE THREAD

**Issue by amigo421** [uphy/obsidian-reminder#35]
### Goal or desired outcome of this feature

would be nice to have additional option for recurrent reminders
which adds desired period to current due date and keep unchecked state on click

### Describe the feature

something like (inspired by extended todotxt):
(@2021-08-14 09:37 rec:3day) - recurrent reminder every 3rd day, similar for Nweek, Nmonth, Nyear 
on checkbox click :  re-set date (@2021-08-**_17_** 09:37 rec:3day)

**Comment by brett-teo** [comment]
> You can use the [tasks](https://github.com/schemar/obsidian-tasks) plugin for repeating reminders
> 
>  example.mov

looks like it works for recurring every day with a remind date but not work for recurring months or year, unless you delete the remind date. Examples below you can try
- [ ] every month on the last ⏰ 2022-12-01 00:43 🔁 every month on the last 📅 2023-01-01
- [x] every month on the last ⏰ 2022-11-04 00:43 🔁 every month on the last 📅 2022-12-31 ✅ 2022-11-04
- [ ] every 3 months on the last ⏰ 2022-12-01 00:43 🔁 every 3 months on the last 📅 2023-01-01
- [x] every 3 months on the last ⏰ 2022-11-04 00:43 🔁 every 3 months on the last 📅 2022-12-31 ✅ 2022-11-04
- [ ] every year on the last⏰ 2022-12-01 00:43 🔁 every year on the last 📅 2023-01-01
- [x] every year on the last ⏰ 2022-11-04 00:43 🔁 every year on the last 📅 2022-12-31 ✅ 2022-11-04
