### ISSUE TITLE
[Bug]: Show Reminder

### ISSUE THREAD

**Issue by vincentteoh** [uphy/obsidian-reminder#36]
### Describe the bug

Show reminder feature works on the Obsidian desktop. However, it does not work on the mobile (android version).

### Expected Behavior

Open up the reminder panel

### Steps to reproduce

- call the show reminder from obsidian command palette.

### Operating system

Android

**Comment by uphy** [comment]
In Obsidian Mobile, views are displayed from the hamburger menu in the upper right corner.

https://user-images.githubusercontent.com/1233373/139772578-73e290e1-4a3e-4280-8c08-4b291b3ba75f.mp4

**Comment by vincentteoh** [comment]
The latest update solve the problem. Many thanks!
