### ISSUE TITLE
[Bug]: Calendar popup does not trigger

### ISSUE THREAD

**Issue by gemisigo** [uphy/obsidian-reminder#37]
### Describe the bug

The Calendar popup trigger is set to (@ but it does not trigger the popup.

https://user-images.githubusercontent.com/10984032/140032486-23de02ff-dcd6-4146-bdc6-bc402fc89137.mp

### Expected Behavior

Calendar picker to pop up

### Steps to reproduce

Type (@

### Operating system

Windows

**Comment by uphy** [comment]
Calendar popup is shown only in todo list item.

**Comment by gemisigo** [comment]
I see. But I don't understand. This is a wonderful feature. Why restrict it to tasks only? It would be just as useful for simple list items that aren't tasks. Do you need the item completion indicator to check if it is still active?

**Comment by uphy** [comment]
> Do you need the item completion indicator to check if it is still active?

Yes, it is one of the reason.  Also, I don't need it.

Let me confirm, the reminder works well in your task list, right?

**Comment by gemisigo** [comment]
Yes, indeed, it does. I should have read the manual more carefully. My apologies.

**Comment by uphy** [comment]
No problem.  If you want non-task list reminder, please feel free to suggest as a feature request.
