### ISSUE TITLE
make it play nice with the natural language dates plugin

### ISSUE THREAD

**Issue by imeed166** [uphy/obsidian-reminder#4]
This plugin https://github.com/argenos/nldates-obsidian have the trigger "@" by default so when I write "(@" (without disabling "nldates") then select a date, it removes the "@" so it doesn't recognize the task until I re-add the "@". 

Fortunately, I can change the trigger for "nldates". But for a beginner, it would be nice if he knew this conflict beforehand, maybe add it in the description of this plugin.

Also, the ability to change this plugin trigger would be nice.
Thank you.

**Comment by frvkl** [comment]
Please, also check compatibility with the [kanban plugin](https://github.com/mgmeyers/obsidian-kanban). This plugin per default also uses the @ symbol to insert a due date, but has no reminder function built in. The difference is in the brackets. The kanban plugin uses the {} brackets. It would be great if we could have a setting to choose the bracket type, so the two plugins can complement each other.

**Comment by uphy** [comment]
@frvkl Kanban plugin format is supported in v1.0.6.  Please try it.

**Comment by jroachgit** [comment]
how about using a double '@@'?

**Comment by uphy** [comment]
Oh, I didn't know `@@` trigger.  I will implement it.

**Comment by uphy** [comment]
The format is supported in v1.0.7

**Comment by jroachgit** [comment]
Did you mean, using @@ will enable using your reminder function?
I'm not sure if it will work with tasks. Will need to test it.
Did you give it a go?

**Comment by uphy** [comment]
@jroachgit I have supported Kanban-style time format yesterday. (e.g. `@{2021-09-08} @@{09:20}` )

Perhaps you were expecting to see calendar popup when you typed `@@`...?

**Comment by uphy** [comment]
Added feature to customize popup trigger. (`Editor > Calendar popup trigger`)
Also, you can choose which reminder format to use by setting (`Reminder Format > Primary reminder format`)

![Kapture 2021-09-10 at 09 41 40](https://user-images.githubusercontent.com/1233373/132780531-407f4f89-0b2c-4317-bd12-a70c8500256d.gif)
