### ISSUE TITLE
No time, no reminder

### ISSUE THREAD

**Issue by mrkuramoto** [uphy/obsidian-reminder#41]
### Goal or desired outcome of this feature

I'd like to have an option to turn off notification for tasks without time. I have tried to leave the time of reminder blank in settings, but this app refused to accept it. 

### Describe the feature

Just a button to turn off notification for task without a specific time

**Comment by imeed166** [comment]
If you want a task with a date and no time, shouldn't you use the [tasks](https://github.com/schemar/obsidian-tasks) plugin instead of the reminder plugin ?

**Comment by uphy** [comment]
I feel it is not a reminder but a due date.
It should be in a different format because it has a different meaning.

Currently obsidian-reminder plugin supplies *reminder* feature.
Therefore, unfortunately, I think your request is out of the scope of the plugin.

**Comment by mrkuramoto** [comment]
> I feel it is not a reminder but a due date. It should be in a different format because it has a different meaning.
> 
> Currently obsidian-reminder plugin supplies _reminder_ feature. Therefore, unfortunately, I think your request is out of the scope of the plugin.

I love the remind plugin, and I have been using it every day. I use it when I have time to make something, and I lave a lot throughout the day. My request is the ability to turn off notifications for tasks that don't have time. I need to see them, but I don't need a pop-up reminder. For example, if I create ten tasks with no time, Reminder will deploy ten reminders that I don't need.

**Comment by uphy** [comment]
I'm very glad you use this plugin heavily!

> My request is the ability to turn off notifications for tasks that don't have time.

Of course, I can implement the feature, but I think such a specific feature request is extremely rare.
It may be useful for you, but we believe it will only complicate the plugin function for many people.

>  if I create ten tasks with no time, Reminder will deploy ten reminders that I don't need.

I think we should resolve THIS issue with another way.

For example, 
- introduce throttling to the reminder (e.g, 1 reminder per minute)
- Show all reminders in one notification modal
- etc.

**Comment by mrkuramoto** [comment]
Hi Yuhi, thank you for your prompt answer - I will follow your advice.
