### ISSUE TITLE
When I updated reminder 1.1.4, it stopped appearing in the sidebar in Windows 10 obsidian 1.13.14.

### ISSUE THREAD

**Issue by rakugakijin** [uphy/obsidian-reminder#46]
Please DO NOT create this type of issue.

Instead, feel free to ask questions in Discussions:
https://github.com/uphy/obsidian-reminder/discussions/new

**Comment by uphy** [comment]
Not reproduced with my clean environment.

Possible reasons:
- Compatibility with other plugins
- The location of the reminder list view is reset (It's in the other sidebar?)

![Kapture 2021-12-29 at 15 52 57](https://user-images.githubusercontent.com/1233373/147635274-85687c97-edd0-40ed-942a-48bd615fccca.gif)
