### ISSUE TITLE
[Bug]: Reminder not set after creating

### ISSUE THREAD

**Issue by kenmoome** [uphy/obsidian-reminder#49]
### Describe the bug

I tried to add a reminder by selecting the date on the pop up calendar modal. But upon clicking on it, the window closes immediately, and the reminder wasn't added. 

This is what I see afterward: 
![image](https://user-images.githubusercontent.com/97150920/148173033-92593753-55db-481c-8b34-aef1b46e99ca.png)

What should I do? 

### Expected Behavior

A reminder should be added with the due date being displayed beside the task.

### Steps to reproduce

1) Type (@ , a calender pop up modal will appear.
2) Nothing happens after selecting on the due date. 

### Operating system

Windows

**Comment by uphy** [comment]
Can you try with clean environment (no plugins, no custom css,...) ?
That doesn't reproduced in my environment.

**Comment by uphy** [comment]
It seems not a todo list item.
Must be

```md
- [ ] Test (@
```
