### ISSUE TITLE
[Bug]: Creating a Folder on Mobile Crashes Obsidian with Reminder Enabled

### ISSUE THREAD

**Issue by iamrecursion** [uphy/obsidian-reminder#59]
### Describe the bug

Creating a folder in the Obsidian file explorer causes Obsidian to soft-crash (reload) when Reminder is enabled. This happens even when it is the _only_ plugin enabled.

The only thing I can think of is that it may be related to indexing. The vault is very large (~17000 files), and I can't reproduce it with smaller vaults (~3000 files).

### Expected Behavior

The folder should be created and Obsidian shouldn't crash.

### Steps to reproduce

1. Enable `Reminder` as the only plugin.
2. Create a folder called `Test`.
3. Obsidian will crash.

### Operating system

iOS,  Obsidian Version 1.1.0 (37)

**Comment by iamrecursion** [comment]
I have a branch with a fix for this issue, as well as a fix for a crash that caused Obsidian mobile to loop on startup. Are PRs welcome?

**Comment by uphy** [comment]
Sorry for late reply.
Yes, PRs are welcome!

**Comment by iamrecursion** [comment]
No prob! PR is up in #78! ^^
