### ISSUE TITLE
customizable "remind me later"

### ISSUE THREAD

**Issue by imeed166** [uphy/obsidian-reminder#6]
It would be nice if we could add more options (1 min, 10 min...) in the settings of the plugin or if we could just write the next time in this panel, thank you.
![image](https://user-images.githubusercontent.com/38974541/131087002-107f9529-e708-47e2-9378-eea272b9bb83.png)

**Comment by wenlzhang** [comment]
It would be great if one can also use Natural Language Dates for defining the next reminder time, which is similar to what is suggested here:

[make it play nice with the natural language dates plugin · Issue #4 · uphy/obsidian-reminder](https://github.com/uphy/obsidian-reminder/issues/4)

**Comment by uphy** [comment]
@imeed166 @wenlzhang I've implemented this setting.  Is this setting satisfies your needs?

<img width="1575" alt="image" src="https://user-images.githubusercontent.com/1233373/131272574-36acf105-166e-4184-8a68-132c4bd492b5.png">

**Comment by imeed166** [comment]
Yes, amazing implementation, but can you check https://github.com/uphy/obsidian-reminder/issues/5#issuecomment-908202345 it's related to the postponing feature

**Comment by uphy** [comment]
As we talked in the issue, I've created another issue.
https://github.com/uphy/obsidian-reminder/issues/15

I close this issue, too.

**Comment by wenlzhang** [comment]
> I've implemented this setting. Is this setting satisfies your needs?

Yes. This should do the work. Thanks for this. @uphy
