### ISSUE TITLE
[Bug]: <TITLE>Plugin is not working

### ISSUE THREAD

**Issue by prdlik007** [uphy/obsidian-reminder#60]
### Describe the bug

1. I write (@ - calendar pops up
2. I click on date - nothing happens
3. Calendar disapears and and I see only text (@

Obsidian 0.13.24
Minimal theme

![image](https://user-images.githubusercontent.com/99074493/152638574-9bd82ed9-61cc-40c3-b768-742afcbc6286.png)
![image](https://user-images.githubusercontent.com/99074493/152638584-64dff52c-5d3d-4e0d-a773-0e419c5de5e9.png)
 

### Steps to reproduce

See above.

### Operating system

Windows

**Comment by sbeugen** [comment]
Same here on MacOS

**Comment by bhean** [comment]
I can't see even the popup (nothing happens when I write `(@` )
Obsidian: 0.13.23

**Comment by prdlik007** [comment]
Still not working even after last update.

**Comment by redreamality** [comment]
I sort of figure out why this not working by reading the source code.
This plugin only works in the environment of a Todo list, not anywhere.

Since many got same need of adding a non-todo reminder, may we discuss the logic there, otherwise I'm not able to directly fire a pull request.

**Comment by prdlik007** [comment]
Oh, this is new and important information for me. I din´t know that. 

It is OK. I will adapt to it now.

**Comment by uphy** [comment]
README and manual documents explain that this plugin uses TODO list for reminder.

- https://github.com/uphy/obsidian-reminder/blob/master/README.md
- https://uphy.github.io/obsidian-reminder/

I feel there are no problems.
