### ISSUE TITLE
Remind me later - Enable format in X days/weeks/months

### ISSUE THREAD

**Issue by okramovic** [uphy/obsidian-reminder#62]
### Goal or desired outcome of this feature

I'd be happy to be able to set reminder to pop up in X days etc, as title says

### Describe the feature

I'd be happy to be able to set reminder to pop up in X days etc, as title says

**Comment by Tback1** [comment]
I'd like to this too

**Comment by uphy** [comment]
Thank you for the feature request.  I've implemented it in v1.1.8:
https://github.com/uphy/obsidian-reminder/releases/tag/1.1.8

**Comment by worrel** [comment]
@uphy I think there may be an issue with this feature - I keep getting prompted for reminders for overdue tasks & selecting "Remind me in 1 hour" doesn't make them go away - they pop up again a few seconds later

**Comment by uphy** [comment]
`In 2 days` should work.

**Comment by uphy** [comment]
@Tback1 Thanks for checking!  I have updated the manual, too.
