### ISSUE TITLE
[Bug]: System notifications on android for reminders not firing

### ISSUE THREAD

**Issue by pcause** [uphy/obsidian-reminder#64]
### Describe the bug

On Android 12, I set a reminder and have the "use system reminders" enabled.  I get the obsidian popup but no system reminder.  using the latest mobile insider build

### Expected Behavior

Get a system reminder

### Steps to reproduce

see above problem description

### Operating system

Android

**Comment by uphy** [comment]
not a bug:
https://github.com/uphy/obsidian-reminder#faq

**Comment by singlerecordnet** [comment]
if a hipothetical 2nd app would be listening to some signal, could this be supplemented? according to https://stackoverflow.com/questions/5745243/data-sharing-between-two-applications both apps would need to have the same sharedId and sharedIdLabel in the respective manifests. Assuming Obsidian Android's manifest.xml isn't public information, but assuming we can somehow have the devs give that information to us (if it even exists) this would technically make the system notifications possible, no? Possibly a feature request for the devs? It would open up additional the capability to have "granularized permissions" and custom functionality, like being able to query the Data-View plugin exactly like you would any other DB.
