### ISSUE TITLE
[Question]: What template do you use for your documentation website?

### ISSUE THREAD

**Issue by GitMurf** [uphy/obsidian-reminder#65]
### Goal or desired outcome of this feature

What template do you use for your documentation website? I love it and am getting ready to create my own docs and would like to explore whatever you used to create your docs website :) Thanks!

### Describe the feature

See above...

**Comment by GitMurf** [comment]
Thanks in advance @uphy !

**Comment by uphy** [comment]
https://discord.com/channels/686053708261228577/707816848615407697/946183267986599946
