### ISSUE TITLE
[Bug]: Console log error about "EditorView.update not allowed"

### ISSUE THREAD

**Issue by GitMurf** [uphy/obsidian-reminder#66]
### Describe the bug

Getting this error in console logs when I start to initiate a reminder with `(@`

![image](https://user-images.githubusercontent.com/64155612/155424205-ad8b8438-3e97-4b7f-812a-8bcf0f3fce50.png)

### Expected Behavior

Not sure. No error should be in the console.

### Steps to reproduce

Type the following into a new line and look at console logs. You will get the error. `This is something to remind (@`

### Operating system

Windows

**Comment by uphy** [comment]
Please follow https://github.com/uphy/obsidian-reminder/issues/45.
