### ISSUE TITLE
[Bug]: Scanning of Reminders does not work corrrect in big databases

### ISSUE THREAD

**Issue by L00tz1ffer** [uphy/obsidian-reminder#71]
### Describe the bug

In have a big database, - like 60-70 notes.

Since the vault grew in the last weeks i added dozens of appending events.

some of them - mostly those in the structure, which were nearer to the root work fine, but the more i get down the tree, items don´t even load if i open the note directly!!!

This bug does NOT occure everytime, it has a certain randomness in its occurrence. sometime its there, sometime its not - while the  note stays the same, and the event too

### Expected Behavior

the scanning for reminders should go deep down the rabbit hole even it is /a/b(c/d/e/f/ and so on

### Steps to reproduce

actually since i now have fixed this bug by recreating every event 
-.- 
i dont have any material for reproduction

### Operating system

Windows

**Comment by uphy** [comment]
If you can't reproduce it, you can't fix it.
Please send me a log the next time you reproduce it.

**Comment by L00tz1ffer** [comment]
it seems, that some notes were only scanned if i open them with the editor, due to private notes of clients i really cannot upload screenshots.

it also seems that Sometimes aswell note scanning is quite slow - especially in the big databases...

**Comment by uphy** [comment]
#78 should fix this issue.
If you encountered this issue again, please feel free to re-open.
