### ISSUE TITLE
[Feature]: Recognise extended checkbox values. Ideally customisable

### ISSUE THREAD

**Issue by RobColes** [uphy/obsidian-reminder#84]
### Goal or desired outcome of this feature

Recognise use of extended checkbox values when reminding or in the list of upcoming/overdue reminders.

A number of themes including minimal now support extended checkboxes e.g. using "- [-]" for cancelled. I would like to be able to use these extended checkboxes and have the reminders plug-in respect their intention.

### Describe the feature

Maybe have a user-maintainable list of checkboxes that are treated as "done" from a reminders point of view, not just using "- [x]"

My use-case:
I pre-fill my Daily note from my calendar at the start of the day.  The daily stuff will be carried forward automatically to tomorrow as a "done" for stand-up and it is useful to know that there was a cancelled meeting.  

As a work-around I am removing the reminder time, but it would be good not to have to.

Many thanks for providing the plug-in!

### Screenshots, mockups, or videos

![image](https://user-images.githubusercontent.com/1765065/169170957-a5aac22c-05b7-4764-9e08-47c1b19220e5.png)

**Comment by 702573n** [comment]
Very important point. Working with Reminder Plugin at this point impossible using alternative checkmarks. Unfortunately cancelled tasks are very often on each working day.

**Comment by zxf4399** [comment]
Any progress？

**Comment by axb21** [comment]
I would very much like this feature too. 

A minimum viable version, at least for me: allow user to add symbols that indicate task is "done" from the perspective of reminders. For instance, right now when task is marked "[x]", it is removed from reminder list and notifications aren't displayed anymore. I'd like cancelled tasks, which are marked with "[-]", to have the exact same behavior. If this plugin allowed user to configure the list of symbols used to decide when a task is "done", I could achieve this by adding '-' to the list alongside 'x'. 

Obviously there are better/fancier ways to handle extended checkbox values that are tuned to the meaning of each extended checkbox character, but it seems to me that what I outlined above ought to be simple to add (?) and would at least add a useful capability.

**Comment by julianmateu** [comment]
+1 I've tested this locally very quickly by changing the file in `.obsidian/plugins/obsidian-reminder-plugin/main.js`, looking for the `isChecked` function and adding the `'-'` value (see [this PR](https://github.com/uphy/obsidian-reminder/pull/191)). I will add tests to the PR, and investigate the option of making this customizable, and add all "done" values that the tasks plugin considers as done.
