### ISSUE TITLE
Support automatically adding customized timestamp after completing tasks

### ISSUE THREAD

**Issue by wenlzhang** [uphy/obsidian-reminder#9]
Similar to what is used for scheduling tasks, it would be great if timestamp can also be added automatically when completing tasks managed by this plugin. The format can be something like the following:
[Support customizing data and time into ISO format · Issue #8 · uphy/obsidian-reminder](https://github.com/uphy/obsidian-reminder/issues/8)

Supporting adding task completing timestamp would also help integrating with Obsidian Tasks, which can filter tasks based on task completion date:
[schemar/obsidian-tasks: Task management for the Obsidian knowledge base.](https://github.com/schemar/obsidian-tasks)

**Comment by uphy** [comment]
@wenlzhang When you use tasks plugin format, done date will be inserted with v1.0.5.  Please try it.

**Comment by uphy** [comment]
![done-date](https://user-images.githubusercontent.com/1233373/131495266-61f0cc60-3d00-4e5f-afde-67bdd1bdfc77.gif)

**Comment by wenlzhang** [comment]
This looks awesome!

Similar to the discussion as follows, a space between the symbol and completion date would look better for me. 
https://github.com/uphy/obsidian-reminder/issues/10#issuecomment-909177459

Also, Tasks uses a space between the symbol and the (completion) date, I am not sure if it would work without a space, if one wants to query completed tasks by using Tasks.

Moreover, is it possible to insert the time info when completing tasks, e.g. `2021-08-31 14:18`? In case that some users may not want to attach the time info, it would be great if one can customize the date format for completing tasks. Specifically, one may define the two date and time formats: "Date and time format for identifying reminders" and "Date and time format for completing tasks".

**Comment by wenlzhang** [comment]
After further testing, I observed the following:

- When completing tasks, the original reminder date together with the completion date would be moved/appended to the end of the task.
  - For instance, `- [ ] Task #Reminder 📅 2021-08-31 #Task #Life 📅 2021-09-30` would become `- [ ] Task #Reminder (there are two spaces here, originally one) #Task #Life 📅 2021-09-30 📅2021-08-31 ✅2021-08-31`
  - Is it possible to keep the reminder date where it is and only append the completion date at the end?
- If the reminder only has date info but no time info, the time info would not be attached to the new reminder when postpone it by say 30 minutes.
  - For instance, `- [ ] Task #Reminder 📅 2021-08-31 #Task #Life 📅 2021-09-30` would become `- [ ] Task #Reminder 📅 2021-08-31 #Task #Life 📅 2021-09-30`, instead of `- [ ] Task #Reminder 📅 2021-08-31 09:30 #Task #Life 📅 2021-09-30`.
  - For this reason, one continues to receive the reminder notification.
- The reminder works whether there is a space or not between the symbol and the reminder date.

I also notice that one can already change the reminder from desktop notifications on macOS. Great work! 😃

**Comment by uphy** [comment]
It will be fixed in the next release!

**Comment by uphy** [comment]
The issue should be fixed in v1.0.6.

**Comment by wenlzhang** [comment]
> As long as you use tasks plugin format, this cannot be fixed.
> Tasks plugin doesn't support date and time format.

Indeed. The current version of Tasks plugin does not support time info. @schemar I assume time info may be supported in the future, considering the following discussion?

[Add optional time in addition to date to "due" · Discussion #64 · schemar/obsidian-tasks](https://github.com/schemar/obsidian-tasks/discussions/64)

Also, the following discussions may be relevant:

- [Make date format configurable (including links like [[2021-04-05]]) · Discussion #69 · schemar/obsidian-tasks](https://github.com/schemar/obsidian-tasks/discussions/69)
- [Add scheduling to tasks · Discussion #67 · schemar/obsidian-tasks](https://github.com/schemar/obsidian-tasks/discussions/67)

**Comment by uphy** [comment]
*Reminder with time*

You can use custom emoji ⏰ for adding time info now.

*Done Date with time*

Needs Tasks plugin's support.

**Comment by wenlzhang** [comment]
Thanks for the update!

I realize that "Done Date" is already supported by Reminder, if the Tasks format is used. For "Done Time", I'll wait for Tasks' support on this. 😃
