### ISSUE TITLE
[Bug]: Click on Overdue tasks does not lead to (not on which) task (is written)

### ISSUE THREAD

**Issue by FrankZter** [uphy/obsidian-reminder#96]
### Describe the bug

When I click on an overdue task (in the reminder pane) the Note on which the task is written is not shown.
![Bild1](https://user-images.githubusercontent.com/70097264/177957185-101985c4-6400-4e5d-bffb-6e1b468dcd50.png)
 

### Expected Behavior

Normally, when I click on a task in the reminder Pane the programm jumps to the note on which the tasks is written.

### Steps to reproduce

Create a task, let it become overdue or just set the due date to yesterday and then click on the task in the reminder pane.

### Operating system

Windows

**Comment by uphy** [comment]
This is expected behavior.
Please click the file link instead:
<img width="645" alt="image" src="https://user-images.githubusercontent.com/1233373/178007229-5f823e4c-eb71-4364-83b2-a17f8ffb3494.png">

**Comment by FrankZter** [comment]
But why can I click on a task that is not overdue and then the page on which the task is written opens up?

**Comment by FrankZter** [comment]
> This is expected behavior. Please click the file link instead: <img alt="image" width="645" src="https://user-images.githubusercontent.com/1233373/178007229-5f823e4c-eb71-4364-83b2-a17f8ffb3494.png">

You don't understand me, I'm afraid. I have the list of tasks in the Reminder pane on the right. All tasks are listed there. If I click on a task there, I get to the task. This is important because I have tasks on pages that describe the context to the task. So I describe the task only briefly and then by clicking on the task, I can look at the context information about the task on the respective page.

This is not possible if the task is overdue. But the function is available (for not overdue tasks) why not for overdue tasks?

**Comment by CalmDownMonkey** [comment]
@FrankZter did you ever find a workaround or another plugin that does something similar to this one but without this problem?
I have a bunch of overdue reminders and I don't know what to do with them since it would take too long to manually Ctrl+F through my notes to try to find them in order to tick them off. I can't continue to use this plugin without a way of handling this extremely common scenario.

**Comment by FrankZter** [comment]
Unfortunately, no. I've now gone through every single overdue task by searching for them using the search function and manually changing the due date (probably just like you did). I also find @uphy's response a bit harsh/very dismissive. I think I described my problem quite friendly. But he has unfortunately made it very clear that he is not so interested.

**Comment by FrankZter** [comment]
@CalmDownMonkey I found a workaround. In the Obsidian controlpanel I found the reminder Hotkeys (did'mt look them up until noe, cos I did not need them) and there it says:
![image](https://user-images.githubusercontent.com/70097264/183385355-82f549f2-8b02-44d9-958b-6ad4bc181471.png)
and if you use "Scan Reminders" the Tasklist is transformed. Now there is no more category "overdue" but only dates and here all tasks are clickable again. So, if one or more dates have slipped into the "overdue" category, you can find them faster with this workaround and change the date.

**Comment by FrankZter** [comment]
@CalmDownMonkey now it works! Yo can click on overdue tasks now and then the notification Window pops up! Thanks @uphy 😘

**Comment by CalmDownMonkey** [comment]
@FrankZter Nice find!! That fixes the problem entirely. I'm not sure why it works this way, but it's a small price to pay if it means fixing the problem and being able to use this great plugin. Thanks for sharing!
